# Generated by Django 4.2.13 on 2024-05-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='available_seats',
        ),
    ]
