# Generated by Django 4.2.13 on 2024-05-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_booking_amount_remove_booking_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_count',
            field=models.IntegerField(default=1),
        ),
    ]
