# Generated by Django 5.1.6 on 2025-02-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_ticket_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie1',
            new_name='Movie',
        ),
    ]
