# Generated by Django 5.1.6 on 2025-02-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_movie1_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cinematography',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='composer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Композитор'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='editor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Монтажер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Продюсер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_designer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Художник по постановке'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenplay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сценарист'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета'),
        ),
    ]
