# Generated by Django 5.1.6 on 2025-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_hall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={},
        ),
        migrations.AddField(
            model_name='hall',
            name='row_number',
            field=models.IntegerField(default=5, verbose_name='Количество рядов'),
        ),
        migrations.AddField(
            model_name='hall',
            name='seats_per_row',
            field=models.IntegerField(default=10, verbose_name='Мест в ряду'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seating_plan',
            field=models.JSONField(blank=True, default=dict, verbose_name='Схема мест'),
        ),
    ]
