# Generated by Django 5.1.6 on 2025-02-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_hall_options_hall_row_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
    ]
