# Generated by Django 5.1.6 on 2025-02-11 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_hall_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.hall'),
        ),
    ]
