# Generated by Django 5.1.6 on 2025-02-15 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_session_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.movie', verbose_name='Фильм'),
        ),
    ]
